public class JWTBearerFlow {

    public static String getAccessToken(String tokenEndpoint, JWT jwt) {
    	system.debug('tokenEndpoint::'+tokenEndpoint);
        system.debug('jwt::'+jwt);
        String access_token = null;
        String body = 'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=' + jwt.issue();
        system.debug('body::'+body);
        HttpRequest req = new HttpRequest();                            
        req.setMethod('POST');
        req.setEndpoint(tokenEndpoint);
        req.setHeader('Content-type', 'application/x-www-form-urlencoded');
        req.setBody(body);
        Http http = new Http();               
        HTTPResponse res = http.send(req);
        system.debug('res::'+res);
        
        if ( res.getStatusCode() == 200 ) {
            system.debug('res.getBody()::'+res.getBody());
            System.JSONParser parser = System.JSON.createParser(res.getBody());
            while (parser.nextToken() != null) {
                if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'access_token')) {
                    parser.nextToken();
                    access_token = parser.getText();
                    break;
                }
            }
        }
        return access_token;
        
    }

}